modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "entris"
version = "0.1.0"
displayName = "Entris"
authors = "Slainlight"
description = '''
More Exciting Enchanting
'''
logoFile = "icon.png"

[[mixins]]
config = "entris-common.mixins.json"

[[dependencies.entris]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"

[[dependencies.entris]]
modId="neoforge"
type="required"
versionRange="[0,)"